import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const schemes = [
  // ===== FEDERAL / PM SCHEMES =====
  {
    name: 'Prime Minister\'s National Laptop Scheme',
    provider: 'Government of Pakistan / HEC',
    category: 'digital',
    description: 'Free laptops for meritorious students in public and private sector universities. Phase 6 (2025-2026) distributing 100,000 laptops based on academic merit. Students with 60%+ marks in public universities and 70%+ in private universities are eligible.',
    eligibilityCriteria: 'Must be enrolled in a HEC-recognized university (public or private). Minimum 60% marks (public sector) or 70% marks (private sector) in last qualifying exam. Must not have received a laptop under any previous government scheme. Age limit: 26 years for undergraduate, 30 for graduate.',
    applicationProcess: 'Apply online through HEC PM Laptop Scheme portal (pmnls.hec.gov.pk) during open registration. University verifies academic record and enrollment. Merit list prepared based on CGPA/marks. Laptops distributed at university campuses.',
    deadline: new Date('2026-12-31'),
    amount: 150000,
    currency: 'PKR',
    website: 'https://hec.gov.pk',
    province: 'all',
    targetAudience: 'Meritorious undergraduate and graduate students across Pakistan',
    status: 'active',
    sourceUrl: 'https://www.hec.gov.pk/english/services/students/pmnls/Pages/How-to-Apply.aspx',
    sourceName: 'HEC PM Laptop Scheme Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Minimum 60% marks (public) or 70% marks (private) in last qualifying exam', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in HEC-recognized university (undergraduate or graduate)', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 26 years (undergraduate) or 30 years (graduate)', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not have received laptop under any previous government scheme', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid CNIC or B-Form', isRequired: true },
      { documentName: 'Academic Marksheet', description: 'Previous exam marksheets showing required marks', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment verification from university', isRequired: true },
      { documentName: 'Photographs', description: '2 recent passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'PM Youth Business & Agriculture Loan Scheme',
    provider: 'Government of Pakistan / PMYP',
    category: 'loan',
    description: 'Subsidized loans for youth entrepreneurs and farmers. Loans up to PKR 7.5 million at low markup rates. IT/E-Commerce businesses get special rates. Available through partner banks (HBL, NBP, MCB, Bank Alfalah, Sindh Bank, ZTBL, BOP). Age 21-45 years.',
    eligibilityCriteria: 'Pakistani citizen aged 21-45 years with valid CNIC. Must have a viable business plan or agricultural activity. Must not be a defaulter of any bank. For IT/E-Commerce: age can be 18-45. Can avail maximum two loans (one long-term, one short-term) within Rs 7.5 million limit.',
    applicationProcess: 'Apply online at pmybals.pmyp.gov.pk or through partner banks. Submit business plan and required documents. Bank evaluates application. Approved loans disbursed with subsidized markup. Repayment in easy monthly installments.',
    deadline: new Date('2026-12-31'),
    amount: 7500000,
    currency: 'PKR',
    website: 'https://pmybals.pmyp.gov.pk',
    province: 'all',
    targetAudience: 'Youth entrepreneurs and farmers aged 21-45',
    status: 'active',
    sourceUrl: 'https://pmybals.pmyp.gov.pk',
    sourceName: 'PM Youth Program Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'age', requirementValue: 'Between 21-45 years (18-45 for IT/E-Commerce)', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must have viable business plan or agricultural activity', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not be a bank defaulter', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must hold valid CNIC', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Business Plan', description: 'Detailed business plan', isRequired: true },
      { documentName: 'Bank Statement', description: 'Last 6 months bank statement', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Educational certificates', isRequired: false },
      { documentName: 'References', description: 'Two references from notable persons', isRequired: false },
    ],
  },
  {
    name: 'PM Youth Skills Development Program',
    provider: 'Government of Pakistan / NAVTTC / PSDF',
    category: 'training',
    description: 'Free vocational and technical skills training for youth aged 18-35. Covers IT, agriculture, health, construction, and other in-demand skills. Training provided at NAVTTC and partner institutes across Pakistan with monthly stipend during training.',
    eligibilityCriteria: 'Age between 18-35 years. Minimum education: Matriculation. Must be a Pakistani citizen. Must not be currently employed. Must not have received similar training from government before.',
    applicationProcess: 'Apply online at navttc.gov.pk or visit nearest NAVTTC center. Register for preferred course. Appear for entrance assessment. Shortlisted candidates enrolled in 3-6 month training programs. Training provided free of cost with monthly stipend.',
    deadline: new Date('2026-12-31'),
    amount: 0,
    currency: 'PKR',
    website: 'https://navttc.gov.pk',
    province: 'all',
    targetAudience: 'Unemployed youth seeking technical skills',
    status: 'active',
    sourceUrl: 'https://navttc.gov.pk',
    sourceName: 'NAVTTC Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'age', requirementValue: 'Between 18-35 years', isRequired: true },
      { requirementType: 'education', requirementValue: 'Minimum Matriculation', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be Pakistani citizen', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not be currently employed', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Educational Certificates', description: 'Matric and above certificates', isRequired: true },
      { documentName: 'Photographs', description: '4 recent passport-size photographs', isRequired: true },
      { documentName: 'Domicile', description: 'Provincial domicile certificate', isRequired: false },
    ],
  },
  {
    name: 'PM Youth Training Program (Paid Internship)',
    provider: 'Government of Pakistan / NAVTTC',
    category: 'training',
    description: 'Provides 12-month paid internships to fresh graduates across public and private sector organizations. Aims to bridge the gap between education and employment by providing hands-on work experience. Monthly stipend of PKR 25,000 provided by government.',
    eligibilityCriteria: 'Must be a fresh graduate (within 3 years of graduation). Age limit 28 years. Must have completed 16 years of education. Must not have any prior work experience. Must pass the program aptitude test.',
    applicationProcess: 'Apply online during announcement period. Appear for aptitude test at designated centers. Shortlisted candidates interviewed. Selected candidates placed in organizations for 12-month internship. Monthly stipend provided by government.',
    deadline: new Date('2026-08-31'),
    amount: 25000,
    currency: 'PKR',
    website: 'https://youth.gov.pk',
    province: 'all',
    targetAudience: 'Fresh graduates seeking employment experience',
    status: 'active',
    sourceUrl: 'https://youth.gov.pk',
    sourceName: 'PM Youth Program Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: '16 years of education (Bachelor\'s degree minimum)', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 28 years', isRequired: true },
      { requirementType: 'other', requirementValue: 'Fresh graduate within 3 years of completing degree', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not have prior work experience', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'Degree Certificate', description: 'Bachelor\'s degree or equivalent', isRequired: true },
      { documentName: 'Transcripts', description: 'All academic transcripts', isRequired: true },
      { documentName: 'Experience Certificate', description: 'Certificate of no prior work experience', isRequired: true },
      { documentName: 'Photographs', description: '4 recent passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'PM Youth Sports Program',
    provider: 'Government of Pakistan',
    category: 'sports',
    description: 'Financial support and training opportunities for talented young athletes across Pakistan. Provides sports kits, training at national academies, and sponsorship for international competitions. Covers all major sports including cricket, hockey, wrestling, boxing, and athletics.',
    eligibilityCriteria: 'Age between 14-25 years. Must have demonstrated athletic ability at district/provincial level. Must not have any criminal record. Must be enrolled in educational institution or have completed education.',
    applicationProcess: 'Apply through district sports officer. Attend trials at designated sports complex. Selected athletes undergo provincial and national level trials. Chosen athletes receive funding and training facilities.',
    deadline: new Date('2026-09-30'),
    amount: 200000,
    currency: 'PKR',
    website: 'https://youth.gov.pk',
    province: 'all',
    targetAudience: 'Young athletes aged 14-25',
    status: 'active',
    sourceUrl: 'https://youth.gov.pk',
    sourceName: 'PM Youth Sports Program',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'age', requirementValue: 'Between 14-25 years', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must have district/provincial level sports achievement', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not have criminal record', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Sports Certificates', description: 'District/provincial level sports certificates', isRequired: true },
      { documentName: 'Medical Certificate', description: 'Fitness certificate from government hospital', isRequired: true },
      { documentName: 'Educational Certificate', description: 'School/college enrollment or completion certificate', isRequired: true },
    ],
  },

  // ===== FEDERAL SCHOLARSHIPS =====
  {
    name: 'Ehsaas Undergraduate Scholarship Program',
    provider: 'Government of Pakistan / BISP / HEC',
    category: 'scholarship',
    description: 'Pakistan\'s largest need-based scholarship program for undergraduate students from low-income families. Covers tuition fees, living stipend, and book allowance. Over 200,000 scholarships awarded annually across 165+ HEC-recognized universities.',
    eligibilityCriteria: 'Family monthly income must be below PKR 45,000. Student must be enrolled in a HEC-recognized university in Pakistan. Must have secured admission on merit. Not receiving any other scholarship. Must not be a government employee.',
    applicationProcess: 'Apply online through HEC Ehsaas portal (ehsas.hec.gov.pk). Submit attested documents to university financial aid office. University verifies and forwards to BISP. Shortlisted candidates are notified via SMS and university notice board.',
    deadline: new Date('2026-03-31'),
    amount: 60000,
    currency: 'PKR',
    website: 'https://ehsas.gov.pk',
    province: 'all',
    targetAudience: 'Low-income undergraduate students across Pakistan',
    status: 'active',
    sourceUrl: 'https://ehsas.gov.pk',
    sourceName: 'Ehsaas Program Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Intermediate (HSSC) or equivalent with minimum 60% marks', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family monthly income below PKR 45,000', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Currently enrolled in HEC-recognized university (1st-8th semester)', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 28 years of age at time of application', isRequired: true },
      { requirementType: 'other', requirementValue: 'Not receiving any other scholarship or financial aid', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must not be a government employee', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'National Identity Card or B-Form of student and father/guardian', isRequired: true },
      { documentName: 'Income Certificate', description: 'Salary slip or income certificate from employer or union council', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment verification from university registrar', isRequired: true },
      { documentName: 'Previous Academic Transcripts', description: 'Matric and Intermediate marksheets attested', isRequired: true },
      { documentName: 'Fee Receipt', description: 'Current semester fee receipt', isRequired: true },
      { documentName: 'Domicile Certificate', description: 'Provincial domicile of student', isRequired: true },
      { documentName: 'Bank Account Details', description: 'Student\'s HBL or Bank Alfalah account number', isRequired: true },
    ],
  },
  {
    name: 'Benazir Undergraduate Scholarship Program',
    provider: 'Benazir Income Support Program (BISP)',
    category: 'scholarship',
    description: 'Continuation of Ehsaas scholarship under new government. Provides need-based financial support to undergraduate students from BISP-enrolled families. Covers full tuition and provides monthly stipend.',
    eligibilityCriteria: 'Student\'s family must be registered with BISP. Must be enrolled in a public sector university. Must have passed intermediate or equivalent exam. Family must be in BISP poverty scorecard with PMT score below 40.',
    applicationProcess: 'Apply through BISP tehsil offices or HEC online portal. Submit required documents. BISP verifies poverty scorecard. University confirms enrollment. Approved students receive direct bank transfers.',
    deadline: new Date('2026-04-15'),
    amount: 80000,
    currency: 'PKR',
    website: 'https://bisp.gov.pk',
    province: 'all',
    targetAudience: 'BISP-enrolled families undergraduate students',
    status: 'active',
    sourceUrl: 'https://bisp.gov.pk',
    sourceName: 'BISP Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Intermediate or equivalent with minimum 50% marks', isRequired: true },
      { requirementType: 'income', requirementValue: 'BISP PMT score below 40', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Currently enrolled in public sector university', isRequired: true },
      { requirementType: 'other', requirementValue: 'Family must be BISP registered', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid CNIC of student and parent/guardian', isRequired: true },
      { documentName: 'BISP Registration Proof', description: 'BISP registration slip or SMS confirmation', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof from university', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'Matric and Intermediate certificates/marksheets', isRequired: true },
      { documentName: 'Bank Account Details', description: 'HBL or Bank Alfalah account in student\'s name', isRequired: true },
    ],
  },
  {
    name: 'HEC Need-Based Scholarship',
    provider: 'Higher Education Commission (HEC)',
    category: 'scholarship',
    description: 'HEC provides need-based scholarships to talented students who cannot afford higher education. Covers tuition fee, monthly stipend, and book allowance. Available at all HEC-recognized public and private universities.',
    eligibilityCriteria: 'Family monthly income below PKR 45,000. Must be enrolled in a HEC-recognized university. Must have passed previous qualifying exam with minimum 50% marks. Must not be receiving any other scholarship.',
    applicationProcess: 'Apply through HEC online portal. Submit documents to university financial aid office. University evaluates and recommends. HEC reviews and approves. Payments released to university directly.',
    deadline: new Date('2026-05-31'),
    amount: 100000,
    currency: 'PKR',
    website: 'https://hec.gov.pk',
    province: 'all',
    targetAudience: 'Low-income students across all provinces',
    status: 'active',
    sourceUrl: 'https://hec.gov.pk',
    sourceName: 'HEC Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Minimum 50% marks in previous qualifying exam', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family monthly income below PKR 45,000', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Currently enrolled in HEC-recognized university', isRequired: true },
      { requirementType: 'other', requirementValue: 'Not receiving any other scholarship or financial aid', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid national identity document', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income proof from employer/union council', isRequired: true },
      { documentName: 'Previous Marksheet', description: 'Attested copies of all previous academic records', isRequired: true },
      { documentName: 'University Enrollment Proof', description: 'Current enrollment verification letter', isRequired: true },
      { documentName: 'Bank Account', description: 'Student\'s bank account details', isRequired: true },
      { documentName: 'Domicile', description: 'Provincial domicile certificate', isRequired: true },
    ],
  },
  {
    name: 'National Talent Hunt Program (NTHP)',
    provider: 'Higher Education Commission (HEC)',
    category: 'scholarship',
    description: 'HEC flagship program to identify and nurture talented students from across Pakistan. Provides comprehensive academic support including tuition fee, stipend, mentoring, and career counseling at partner universities.',
    eligibilityCriteria: 'Must have passed HSSC (Intermediate) or equivalent with minimum 60% aggregate marks. Must have secured admission in a NTHP partner university. Age limit 20 years for undergraduate. Must not have any criminal record.',
    applicationProcess: 'Register online at hec.gov.pk/nthp. Complete online application. Appear for NTHP aptitude test at designated centers. Shortlisted candidates called for interview. Final selection based on test + interview + academic record.',
    deadline: new Date('2026-06-30'),
    amount: 150000,
    currency: 'PKR',
    website: 'https://hec.gov.pk',
    province: 'all',
    targetAudience: 'High-achieving intermediate students',
    status: 'active',
    sourceUrl: 'https://hec.gov.pk',
    sourceName: 'HEC Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'HSSC/Intermediate or equivalent with minimum 60% aggregate marks', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 20 years at time of application', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Must have secured admission in NTHP partner university', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must pass NTHP aptitude test', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid CNIC or B-Form', isRequired: true },
      { documentName: 'HSSC Marksheet', description: 'Intermediate marksheets with attested copies', isRequired: true },
      { documentName: 'University Admission Letter', description: 'Admission offer from NTHP partner university', isRequired: true },
      { documentName: 'Matric Marksheet', description: 'Matriculation certificate and marksheet', isRequired: true },
      { documentName: 'Domicile Certificate', description: 'Provincial domicile certificate', isRequired: true },
      { documentName: 'Photographs', description: '4 recent passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Waseela-e-Taleem (Education Stipend)',
    provider: 'Benazir Income Support Program (BISP)',
    category: 'stipend',
    description: 'Conditional cash transfer program providing education stipend to children of BISP-enrolled families. Covers primary to higher secondary level. Aims to increase school enrollment and reduce dropout rates among poor families.',
    eligibilityCriteria: 'Family must be registered with BISP. Children must be aged 4-18 years. Must be enrolled in a government or BISP-approved private school. Regular school attendance above 80%. Children must have B-Form from NADRA.',
    applicationProcess: 'Register at nearest BISP tehsil office. Provide B-Form of children. BISP verifies family registration. Children\'s school enrollment verified. Stipend payments begin after verification through HBL Konnect or mobile wallets.',
    deadline: new Date('2026-12-31'),
    amount: 3000,
    currency: 'PKR',
    website: 'https://bisp.gov.pk',
    province: 'all',
    targetAudience: 'Children of BISP-enrolled families (age 4-18)',
    status: 'active',
    sourceUrl: 'https://bisp.gov.pk',
    sourceName: 'BISP Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'age', requirementValue: 'Child aged 4-18 years', isRequired: true },
      { requirementType: 'other', requirementValue: 'Family must be BISP registered', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Must be enrolled in government or BISP-approved school', isRequired: true },
      { requirementType: 'other', requirementValue: 'Minimum 80% school attendance', isRequired: true },
    ],
    documents: [
      { documentName: 'B-Form', description: 'NADRA B-Form for each child', isRequired: true },
      { documentName: 'Parent CNIC', description: 'BISP-registered parent CNIC', isRequired: true },
      { documentName: 'BISP Registration Proof', description: 'BISP registration slip or confirmation', isRequired: true },
      { documentName: 'School Enrollment Letter', description: 'Enrollment verification from school', isRequired: true },
    ],
  },
  {
    name: 'Aghosh Program (Mother & Child Health)',
    provider: 'BISP / World Bank',
    category: 'health',
    description: 'Conditional cash transfers to pregnant and lactating women for maternal and child health. Provides nutrition support, health checkups, and education stipend for children. Available in selected districts across Pakistan.',
    eligibilityCriteria: 'Must be pregnant or lactating mother. Must be registered with BISP. Must attend regular health checkups at designated facility. Child must be enrolled in school after reaching age 5.',
    applicationProcess: 'Register at nearest BISP tehsil office during pregnancy. Provide B-Form and medical certificate. BISP verifies and enrolls. Monthly payments begin after first health checkup. Payments increase with child milestones.',
    deadline: new Date('2026-12-31'),
    amount: 8000,
    currency: 'PKR',
    website: 'https://bisp.gov.pk',
    province: 'all',
    targetAudience: 'Pregnant and lactating women from poor families',
    status: 'active',
    sourceUrl: 'https://bisp.gov.pk',
    sourceName: 'BISP / World Bank',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'gender', requirementValue: 'Female (pregnant or lactating mother)', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be BISP registered', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must attend regular health checkups', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC', description: 'Valid National Identity Card', isRequired: true },
      { documentName: 'B-Form', description: 'Family B-Form', isRequired: true },
      { documentName: 'Medical Certificate', description: 'Pregnancy confirmation from health facility', isRequired: true },
      { documentName: 'BISP Registration Proof', description: 'BISP registration confirmation', isRequired: true },
    ],
  },

  // ===== PUNJAB CM SCHEMES =====
  {
    name: 'CM Punjab Honhaar Scholarship Program',
    provider: 'Government of Punjab / Punjab HEC',
    category: 'scholarship',
    description: 'Chief Minister Maryam Nawaz\'s flagship merit-based scholarship program offering 30,000 scholarships for undergraduate students. Covers full tuition fees at public and private universities. Monthly family income must be below Rs 300,000. No age limit. Available for all genders.',
    eligibilityCriteria: 'Must have Punjab domicile (or AJK domicile). No age limit. No gender restriction. Monthly family income must be less than Rs 300,000. Must be enrolled in a recognized university for undergraduate program. Must have passed intermediate with good marks.',
    applicationProcess: 'Apply online at honhaarscholarship.punjabhec.gov.pk. Create account and fill application form. Upload required documents. Application reviewed by Punjab HEC. Selected students notified via portal and SMS. Scholarship disbursed directly to university.',
    deadline: new Date('2026-06-30'),
    amount: 200000,
    currency: 'PKR',
    website: 'https://honhaarscholarship.punjabhec.gov.pk',
    province: 'punjab',
    targetAudience: 'Undergraduate students from Punjab with family income below Rs 300,000/month',
    status: 'active',
    sourceUrl: 'https://honhaarscholarship.punjabhec.gov.pk',
    sourceName: 'CM Honhaar Scholarship Official Portal',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'domicile', requirementValue: 'Punjab domicile required (AJK domicile also accepted)', isRequired: true },
      { requirementType: 'income', requirementValue: 'Monthly family income less than Rs 300,000', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in undergraduate program at recognized university', isRequired: true },
      { requirementType: 'education', requirementValue: 'Passed intermediate/equivalent examination', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid CNIC or B-Form of student', isRequired: true },
      { documentName: 'Punjab Domicile', description: 'Punjab provincial domicile certificate', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income proof (salary slip/affidavit)', isRequired: true },
      { documentName: 'Academic Certificates', description: 'Matric and Intermediate marksheets', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof from university', isRequired: true },
      { documentName: 'Photographs', description: 'Recent passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'PEEF (Punjab Educational Endowment Fund) Scholarship',
    provider: 'Punjab Government / PEEF',
    category: 'scholarship',
    description: 'Merit and need-based scholarship for talented students from Punjab. One of the largest scholarship programs in Pakistan, providing financial support to thousands of students annually for undergraduate and postgraduate studies.',
    eligibilityCriteria: 'Must have Punjab domicile. Must have passed Matric/Intermediate from Punjab boards with at least 60% marks. Family monthly income must be below PKR 30,000 (for need-based). Must be enrolled in a partner university or college in Punjab.',
    applicationProcess: 'Apply online at peef.edu.pk. Submit documents to partner institution. Shortlisting based on academic merit and financial need. Selected students receive scholarship letter via email and post.',
    deadline: new Date('2026-02-28'),
    amount: 120000,
    currency: 'PKR',
    website: 'https://peef.edu.pk',
    province: 'punjab',
    targetAudience: 'Punjab domicile students with good academic record',
    status: 'active',
    sourceUrl: 'https://peef.edu.pk',
    sourceName: 'PEEF Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Matric/Intermediate with minimum 60% marks from Punjab boards', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family monthly income below PKR 30,000', isRequired: true },
      { requirementType: 'domicile', requirementValue: 'Punjab domicile required', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in PEEF partner institution in Punjab', isRequired: true },
      { requirementType: 'other', requirementValue: 'Not receiving any other scholarship', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'National Identity Card or B-Form', isRequired: true },
      { documentName: 'Punjab Domicile', description: 'Valid Punjab domicile certificate', isRequired: true },
      { documentName: 'Income Certificate', description: 'Income certificate from employer or union council', isRequired: true },
      { documentName: 'Board Marksheets', description: 'Attested copies of Matric and Intermediate marksheets', isRequired: true },
      { documentName: 'University Admission Letter', description: 'Admission letter from partner institution', isRequired: true },
      { documentName: 'Fee Challan', description: 'Current semester fee challan/receipt', isRequired: true },
      { documentName: 'Affidavit', description: 'Sworn affidavit declaring not receiving other scholarship', isRequired: true },
    ],
  },
  {
    name: 'Punjab Educational Stipend Program (PESP)',
    provider: 'Punjab Government / School Education Department',
    category: 'stipend',
    description: 'Cash transfer program for students in government schools across Punjab. Provides quarterly stipend to increase enrollment and retention, especially for girls. Covers primary to secondary level education.',
    eligibilityCriteria: 'Must be enrolled in a government school in Punjab. Age 6-16 years for primary, 12-18 for secondary. Family must be in poorest 40% of population. Regular attendance above 80%. Priority given to girls\' education.',
    applicationProcess: 'Enroll child in government school. School headmaster submits enrollment data to district education office. DEO verifies and registers student for PESP. Stipend payments released quarterly through bank accounts.',
    deadline: new Date('2026-12-31'),
    amount: 1500,
    currency: 'PKR',
    website: 'https://pesp.punjab.gov.pk',
    province: 'punjab',
    targetAudience: 'Government school students in Punjab (primary and secondary)',
    status: 'active',
    sourceUrl: 'https://pesp.punjab.gov.pk',
    sourceName: 'Punjab Education Foundation',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Enrolled in Punjab government school (primary or secondary)', isRequired: true },
      { requirementType: 'age', requirementValue: '6-16 years (primary) or 12-18 years (secondary)', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family in poorest 40% of population', isRequired: true },
      { requirementType: 'other', requirementValue: 'Minimum 80% school attendance', isRequired: true },
    ],
    documents: [
      { documentName: 'B-Form', description: 'NADRA B-Form of child', isRequired: true },
      { documentName: 'School Enrollment Letter', description: 'Enrollment verification from school headmaster', isRequired: true },
      { documentName: 'Parent CNIC', description: 'National Identity Card of parent/guardian', isRequired: true },
      { documentName: 'Attendance Record', description: 'School attendance certificate', isRequired: true },
    ],
  },

  // ===== SINDH CM SCHEMES =====
  {
    name: 'SEEF (Sindh Educational Endowment Fund) Scholarship',
    provider: 'Government of Sindh / SEEF',
    category: 'scholarship',
    description: 'Chief Minister Sindh\'s flagship scholarship program providing full fee coverage for meritorious students from Sindh. Covers undergraduate, graduate, and professional programs (Medical, Engineering, etc.) at approved institutions. Minimum CGPA 2.5 required.',
    eligibilityCriteria: 'Must have Sindh domicile and PRC (Permanent Resident Certificate). Must be enrolled in a SEEF-approved institution in Sindh. Minimum CGPA of 2.5 for ongoing students. Family income criteria applies for need-based component.',
    applicationProcess: 'Apply online at seef.sindh.gov.pk. Create account and fill application. Upload required documents including domicile, PRC, and academic records. Application reviewed by SEEF committee. Selected students notified via portal.',
    deadline: new Date('2026-08-31'),
    amount: 150000,
    currency: 'PKR',
    website: 'https://seef.sindh.gov.pk',
    province: 'sindh',
    targetAudience: 'Sindh domicile students enrolled in approved institutions',
    status: 'active',
    sourceUrl: 'https://seef.sindh.gov.pk',
    sourceName: 'SEEF Official Portal',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'domicile', requirementValue: 'Sindh domicile and PRC required', isRequired: true },
      { requirementType: 'education', requirementValue: 'Minimum CGPA 2.5 (for ongoing students)', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in SEEF-approved institution in Sindh', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be permanent resident of Sindh', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Sindh Domicile', description: 'Sindh provincial domicile certificate', isRequired: true },
      { documentName: 'PRC', description: 'Permanent Resident Certificate of Sindh', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'All academic records/mark sheets', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income certificate', isRequired: false },
    ],
  },
  {
    name: 'Benazir Bhutto Shaheed Scholarship (Sindh)',
    provider: 'Government of Sindh',
    category: 'scholarship',
    description: 'Named after former PM Benazir Bhutto. Provides scholarships to talented students from Sindh, especially from rural and backward districts. Covers tuition fees and provides monthly stipend for undergraduate studies.',
    eligibilityCriteria: 'Must have Sindh domicile. Must have passed intermediate with minimum 55% marks. Must be enrolled in Sindh public university. Priority to students from Tharparkar, Umerkot, Sanghar, and other backward districts.',
    applicationProcess: 'Apply through Sindh government portal. Submit required documents. District committee verifies and recommends. SHEC shortlists based on merit and need. Scholarship disbursed through bank transfer.',
    deadline: new Date('2026-04-30'),
    amount: 75000,
    currency: 'PKR',
    website: 'https://sindhhec.gov.pk',
    province: 'sindh',
    targetAudience: 'Sindh students from backward districts',
    status: 'active',
    sourceUrl: 'https://sindhhec.gov.pk',
    sourceName: 'Sindh HEC',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Intermediate with minimum 55% marks', isRequired: true },
      { requirementType: 'domicile', requirementValue: 'Sindh domicile (priority to backward districts)', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in Sindh public university', isRequired: true },
      { requirementType: 'other', requirementValue: 'Not receiving other scholarship', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Sindh Domicile', description: 'Sindh provincial domicile', isRequired: true },
      { documentName: 'Intermediate Marksheet', description: 'Attested marksheet with 55%+ marks', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income certificate', isRequired: true },
    ],
  },

  // ===== KPK CM SCHEMES =====
  {
    name: 'CMEEF (CM KPK Education Endowment Fund) Scholarship',
    provider: 'Government of KPK / HED',
    category: 'scholarship',
    description: 'Chief Minister Khyber Pakhtunkhwa\'s Education Endowment Fund providing fully-funded scholarships for undergraduate and postgraduate students. Covers all educational expenses plus PKR 5,000/month stipend. Merit-cum-affordability basis.',
    eligibilityCriteria: 'Must have KPK domicile. Must be enrolled in a recognized university for undergraduate or postgraduate program. Must have passed previous exam with good marks. Family income criteria applies for need-based component.',
    applicationProcess: 'Apply through HED KPK portal (hed.gkp.pk). Submit required documents. HED verifies domicile and academic record. Selected students receive scholarship covering all expenses plus monthly stipend of PKR 5,000.',
    deadline: new Date('2026-06-30'),
    amount: 200000,
    currency: 'PKR',
    website: 'https://hed.gkp.pk',
    province: 'kpk',
    targetAudience: 'KPK domicile undergraduate and postgraduate students',
    status: 'active',
    sourceUrl: 'https://hed.gkp.pk/content/chief-minister-educational-endowment-fund-cmeef',
    sourceName: 'HED KPK Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'domicile', requirementValue: 'KPK domicile required', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in recognized university (UG or PG)', isRequired: true },
      { requirementType: 'education', requirementValue: 'Passed previous exam with good academic record', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family income criteria applies', isRequired: false },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'KPK Domicile', description: 'KPK provincial domicile', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'All previous academic records', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income proof', isRequired: false },
      { documentName: 'Bank Account', description: 'Student\'s bank account details', isRequired: true },
    ],
  },

  // ===== BALOCHISTAN CM SCHEMES =====
  {
    name: 'BEEF (Balochistan Education Endowment Fund) Scholarship',
    provider: 'Government of Balochistan / BEEF',
    category: 'scholarship',
    description: 'Balochistan Education Endowment Fund offering fully-funded scholarships for talented and deserving students from all districts of Balochistan. Covers tuition, hostel, and provides monthly stipend. Endowment fund value PKR 5 Billion.',
    eligibilityCriteria: 'Must have Balochistan domicile. Must be enrolled in a recognized university. Must have passed intermediate with minimum 45% marks. Family income below PKR 35,000 per month for need-based component.',
    applicationProcess: 'Apply online at beef.org.pk. Submit required documents. BEEF committee evaluates applications on merit and need. Selected students receive scholarship covering all educational expenses.',
    deadline: new Date('2026-05-15'),
    amount: 120000,
    currency: 'PKR',
    website: 'https://beef.org.pk',
    province: 'balochistan',
    targetAudience: 'Balochistan domicile students across Pakistan',
    status: 'active',
    sourceUrl: 'https://beef.org.pk',
    sourceName: 'BEEF Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'domicile', requirementValue: 'Balochistan domicile required', isRequired: true },
      { requirementType: 'education', requirementValue: 'Intermediate with minimum 45% marks', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in recognized university', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family monthly income below PKR 35,000', isRequired: false },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Balochistan Domicile', description: 'Balochistan provincial domicile', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income certificate from DC office', isRequired: true },
      { documentName: 'Marksheets', description: 'Intermediate marksheets attested', isRequired: true },
      { documentName: 'University Enrollment', description: 'University enrollment proof', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },

  // ===== MILITARY / OTHER SCHEMES =====
  {
    name: 'Fauji Foundation Education Scholarship',
    provider: 'Fauji Foundation',
    category: 'scholarship',
    description: 'Educational support for children of ex-servicemen and martyrs. Covers tuition from primary to university level. Priority given to children of Shuhada (martyrs) and disabled veterans.',
    eligibilityCriteria: 'Must be child of ex-serviceman, Shaheed, or disabled veteran. Must be enrolled in recognized educational institution. Must have passed previous exam with minimum 60% marks. Age limit varies by education level.',
    applicationProcess: 'Apply through nearest Fauji Foundation education office. Submit military service records and educational documents. Fauji Foundation reviews and approves. Scholarship payments released to institution directly.',
    deadline: new Date('2026-06-30'),
    amount: 50000,
    currency: 'PKR',
    website: 'https://ffoundation.org.pk',
    province: 'all',
    targetAudience: 'Children of ex-servicemen and martyrs',
    status: 'active',
    sourceUrl: 'https://ffoundation.org.pk',
    sourceName: 'Fauji Foundation',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Minimum 60% marks in previous exam', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be child of ex-serviceman/Shaheed/disabled veteran', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Must be enrolled in recognized institution', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document of student and father', isRequired: true },
      { documentName: 'Military Service Record', description: 'Father\'s military service certificate or Shaheed certificate', isRequired: true },
      { documentName: 'Academic Certificates', description: 'Previous exam marksheets and certificates', isRequired: true },
      { documentName: 'Institution Enrollment Letter', description: 'Current enrollment verification', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Pakistan Navy Education Trust Scholarship',
    provider: 'Pakistan Navy',
    category: 'scholarship',
    description: 'Merit-based scholarship for children of naval personnel and martyrs. Available for undergraduate and postgraduate studies. Covers tuition, hostel, and provides monthly stipend.',
    eligibilityCriteria: 'Must be child of serving or retired Pakistan Navy personnel or Shaheed. Must have passed intermediate with minimum 65% marks. Must be enrolled in HEC-recognized university. Age limit 25 years.',
    applicationProcess: 'Apply through Pakistan Navy Education Trust office. Submit service records and educational documents. NET evaluates and shortlists. Selected candidates receive scholarship approval letter.',
    deadline: new Date('2026-07-31'),
    amount: 100000,
    currency: 'PKR',
    website: 'https://paknavy.gov.pk',
    province: 'all',
    targetAudience: 'Children of Pakistan Navy personnel and martyrs',
    status: 'active',
    sourceUrl: 'https://paknavy.gov.pk',
    sourceName: 'Pakistan Navy Education Trust',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Intermediate with minimum 65% marks', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 25 years', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be child of Pakistan Navy personnel or Shaheed', isRequired: true },
      { requirementType: 'enrollment', requirementValue: 'Enrolled in HEC-recognized university', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Navy Service Certificate', description: 'Father/mother\'s naval service record', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'Matric and Intermediate marksheets', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof', isRequired: true },
    ],
  },
  {
    name: 'Pakistan Army Education Corps (AEC) Scholarship',
    provider: 'Pakistan Army',
    category: 'scholarship',
    description: 'Provides educational support to children of Army personnel and martyrs. Covers full tuition and boarding expenses. Available for studies within Pakistan and abroad for postgraduate programs.',
    eligibilityCriteria: 'Must be child of serving/retired Army personnel or Shaheed. Must have intermediate with minimum 60% marks. For abroad studies, must have bachelor\'s with minimum 70% marks. Age limit 28 years.',
    applicationProcess: 'Apply through unit education officer or AEC headquarters. Submit military records and educational documents. AEC committee evaluates. Shortlisted candidates may be called for interview.',
    deadline: new Date('2026-08-31'),
    amount: 120000,
    currency: 'PKR',
    website: 'https://pakarmy.gov.pk',
    province: 'all',
    targetAudience: 'Children of Pakistan Army personnel and martyrs',
    status: 'active',
    sourceUrl: 'https://pakarmy.gov.pk',
    sourceName: 'Pakistan Army AEC',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Intermediate with minimum 60% marks (domestic) or Bachelor with 70% (abroad)', isRequired: true },
      { requirementType: 'age', requirementValue: 'Below 28 years', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be child of Pakistan Army personnel or Shaheed', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'Army Service Certificate', description: 'Father/mother\'s army service record', isRequired: true },
      { documentName: 'Academic Transcripts', description: 'All previous academic records', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'University admission/enrollment proof', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
  {
    name: 'Panagah (Student Hostel Scheme)',
    provider: 'Government of Pakistan / PPAF',
    category: 'housing',
    description: 'Provides free or subsidized hostel accommodation to students studying away from home in major cities. Students pay only PKR 500-1000 per month. Hostels equipped with modern facilities including WiFi, library, and study rooms.',
    eligibilityCriteria: 'Must be enrolled in university or college in a city other than hometown. Family income below PKR 50,000 per month. Must have admission letter from institution. Priority to students from remote areas.',
    applicationProcess: 'Apply online at panagah.gov.pk. Submit enrollment and income documents. Hostel committee verifies and allocates room. Students pay nominal monthly fee. Accommodation includes meals and study facilities.',
    deadline: new Date('2026-12-31'),
    amount: 500,
    currency: 'PKR',
    website: 'https://panagah.gov.pk',
    province: 'all',
    targetAudience: 'Students studying away from home',
    status: 'active',
    sourceUrl: 'https://panagah.gov.pk',
    sourceName: 'Panagah Official',
    verificationStatus: 'verified',
    requirements: [
      { requirementType: 'education', requirementValue: 'Must be enrolled in recognized university/college', isRequired: true },
      { requirementType: 'income', requirementValue: 'Family monthly income below PKR 50,000', isRequired: true },
      { requirementType: 'other', requirementValue: 'Must be studying in a city other than hometown', isRequired: true },
    ],
    documents: [
      { documentName: 'CNIC / B-Form', description: 'Valid identity document', isRequired: true },
      { documentName: 'University Enrollment Letter', description: 'Current enrollment proof', isRequired: true },
      { documentName: 'Income Certificate', description: 'Family income proof', isRequired: true },
      { documentName: 'Hometown Proof', description: 'Domicile or permanent address proof', isRequired: true },
      { documentName: 'Photographs', description: '4 passport-size photographs', isRequired: true },
    ],
  },
];

async function main() {
  console.log('Seeding government schemes...');

  await prisma.schemeDocument.deleteMany();
  await prisma.schemeRequirement.deleteMany();
  await prisma.governmentScheme.deleteMany();

  let count = 0;
  for (const scheme of schemes) {
    const { requirements, documents, ...schemeData } = scheme;
    const created = await prisma.governmentScheme.create({
      data: {
        ...schemeData,
        requirements: {
          create: requirements.map(r => ({
            requirementType: r.requirementType,
            requirementValue: r.requirementValue,
            isRequired: r.isRequired,
          })),
        },
        documents: {
          create: documents.map(d => ({
            documentName: d.documentName,
            description: d.description,
            isRequired: d.isRequired,
          })),
        },
      },
    });
    count++;
    console.log(`  ✅ ${count}. ${created.name}`);
  }

  console.log(`\nTotal schemes seeded: ${count}`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
