export interface FraudRule {
  id: string;
  name: string;
  ruleType: 'keyword' | 'pattern' | 'url' | 'behavioral' | 'domain';
  pattern: string;
  severity: 'low' | 'medium' | 'high' | 'critical';
  score: number;
  enabled: boolean;
  description: string;
  category?: string;
}

export interface RuleMatch {
  rule: FraudRule;
  matched: boolean;
  evidence: string;
  matchedContent?: string;
}

const DEFAULT_RULES: FraudRule[] = [
  {
    id: 'OTP_REQUEST',
    name: 'OTP Request',
    ruleType: 'keyword',
    pattern: 'send.*otp|otp.*share|share.*otp|code.*share|verification code',
    severity: 'critical',
    score: 30,
    enabled: true,
    description: 'Detects requests to share OTP or verification codes',
    category: 'credential_theft',
  },
  {
    id: 'PASSWORD_REQUEST',
    name: 'Password Request',
    ruleType: 'keyword',
    pattern: 'password.*share|share.*password|tell.*password|enter.*password',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects requests to share passwords',
    category: 'credential_theft',
  },
  {
    id: 'PIN_REQUEST',
    name: 'PIN Request',
    ruleType: 'keyword',
    pattern: '\\bpin\\b.*share|share.*\\bpin\\b|tell.*\\bpin\\b|enter.*\\bpin\\b',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects requests to share PINs',
    category: 'credential_theft',
  },
  {
    id: 'CVV_REQUEST',
    name: 'CVV Request',
    ruleType: 'keyword',
    pattern: 'cvv.*share|share.*cvv|card.*number.*cvv|cvv.*number',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects requests to share CVV or card details',
    category: 'credential_theft',
  },
  {
    id: 'URGENCY',
    name: 'Urgency Pressure',
    ruleType: 'behavioral',
    pattern: '(urgent|immediately|within\\s+(?:minutes|hours)|act\\s*now|hurry|last\\s*chance|respond\\s+now|do\\s+it\\s+now|don.t\\s+delay)',
    severity: 'high',
    score: 15,
    enabled: true,
    description: 'Detects urgency and pressure tactics',
    category: 'social_engineering',
  },
  {
    id: 'THREAT',
    name: 'Threat Language',
    ruleType: 'keyword',
    pattern: 'account.*block|account.*suspend|account.*close|police.*arrest|legal.*action',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects threatening language about account or legal consequences',
    category: 'social_engineering',
  },
  {
    id: 'PRIZE_SCAM',
    name: 'Prize Scam',
    ruleType: 'keyword',
    pattern: 'congratulations.*won|you.*won|prize.*claim|lucky.*winner',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects prize and lottery scam patterns',
    category: 'scam',
  },
  {
    id: 'FAKE_REFUND',
    name: 'Fake Refund',
    ruleType: 'keyword',
    pattern: 'refund.*claim|money.*back|refund.*process',
    severity: 'medium',
    score: 15,
    enabled: true,
    description: 'Detects fake refund scam patterns',
    category: 'scam',
  },
  {
    id: 'INVESTMENT_SCAM',
    name: 'Investment Scam',
    ruleType: 'keyword',
    pattern: 'guaranteed.*return|double.*money|investment.*opportunity|risk.*free',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects investment and financial scam patterns',
    category: 'scam',
  },
  {
    id: 'JOB_SCAM',
    name: 'Job Scam',
    ruleType: 'keyword',
    pattern: 'job.*offer|work.*from.*home.*earn|easy.*money|part.*time.*earn',
    severity: 'medium',
    score: 15,
    enabled: true,
    description: 'Detects job scam and fake employment patterns',
    category: 'scam',
  },
  {
    id: 'SCHOLARSHIP_SCAM',
    name: 'Scholarship Scam',
    ruleType: 'keyword',
    pattern: 'scholarship.*guaranteed|admission.*guaranteed|visa.*guaranteed',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake scholarship and admission scam patterns',
    category: 'scam',
  },
  {
    id: 'IMPERSONATION',
    name: 'Bank Impersonation',
    ruleType: 'keyword',
    pattern: 'bank.*official|customer.*care.*bank|support.*team.*bank',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects bank impersonation attempts',
    category: 'impersonation',
  },
  {
    id: 'PAYMENT_REQUEST',
    name: 'Payment Request',
    ruleType: 'keyword',
    pattern: 'send.*money|transfer.*money|wire.*transfer|western.*union|crypto.*send',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects requests for money transfers or payments',
    category: 'financial',
  },
  {
    id: 'ACCOUNT_SUSPENSION',
    name: 'Account Suspension Threat',
    ruleType: 'keyword',
    pattern: 'account.*will.*be.*blocked|account.*will.*be.*suspended',
    severity: 'high',
    score: 22,
    enabled: true,
    description: 'Detects threats of account suspension or blocking',
    category: 'social_engineering',
  },
  {
    id: 'URL_SHORTENER',
    name: 'URL Shortener',
    ruleType: 'url',
    pattern: 'bit\\.ly|tinyurl|t\\.co|goo\\.gl|is\\.gd',
    severity: 'medium',
    score: 10,
    enabled: true,
    description: 'Detects use of URL shortening services',
    category: 'url',
  },
  {
    id: 'SUSPICIOUS_TLD',
    name: 'Suspicious TLD',
    ruleType: 'url',
    pattern: '\\.online|\\.xyz|\\.top|\\.buzz|\\.click|\\.work|\\.tk|\\.ml|\\.ga|\\.cf|\\.gq|\\.club|\\.stream|\\.loan|\\.bid|\\.download',
    severity: 'medium',
    score: 8,
    enabled: true,
    description: 'Detects suspicious top-level domains',
    category: 'url',
  },
  {
    id: 'LOOKALIKE',
    name: 'Lookalike Domain',
    ruleType: 'domain',
    pattern: 'paypa1|microsoft-security|apple-support|google-verify|amazon-security|netflix-billing',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects lookalike or typosquatting domains impersonating brands',
    category: 'impersonation',
  },
  {
    id: 'CREDENTIAL_HARVEST',
    name: 'Credential Harvest',
    ruleType: 'keyword',
    pattern: 'verify.*account|confirm.*identity|update.*payment|verify.*information',
    severity: 'medium',
    score: 12,
    enabled: true,
    description: 'Detects credential harvesting attempts',
    category: 'credential_theft',
  },
  {
    id: 'CRYPTO_PRESSURE',
    name: 'Crypto Pressure',
    ruleType: 'keyword',
    pattern: 'bitcoin|ethereum|crypto.*transfer|wallet.*address|blockchain',
    severity: 'medium',
    score: 10,
    enabled: true,
    description: 'Detects cryptocurrency-related pressure tactics',
    category: 'financial',
  },
  {
    id: 'FAKE_JOB_FEE',
    name: 'Fake Job Fee',
    ruleType: 'keyword',
    pattern: 'process.*fee|training.*fee|registration.*fee|joining.*fee',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake job fee requests',
    category: 'scam',
  },
  {
    id: 'SENDER_MISMATCH',
    name: 'Sender Mismatch',
    ruleType: 'domain',
    pattern: 'from.*bank.*@.*gmail|from.*bank.*@.*yahoo|from.*bank.*@.*hotmail',
    severity: 'high',
    score: 15,
    enabled: true,
    description: 'Detects sender email mismatch with claimed bank identity',
    category: 'impersonation',
  },
  {
    id: 'ATTACHMENT_WARNING',
    name: 'Attachment Warning',
    ruleType: 'keyword',
    pattern: 'attached.*file|see.*attached|open.*attachment',
    severity: 'medium',
    score: 8,
    enabled: true,
    description: 'Detects suspicious attachment references',
    category: 'malware',
  },
  {
    id: 'TIME_PRESSURE',
    name: 'Time Pressure',
    ruleType: 'behavioral',
    pattern: '(expires?\\s+(?:today|now|within)|limited\\s+time\\s+(?:offer|deal|only)|only\\s+today|act\\s+before|expires\\s+in\\s+\\d)',
    severity: 'medium',
    score: 12,
    enabled: true,
    description: 'Detects time pressure tactics',
    category: 'social_engineering',
  },
  {
    id: 'MANDATE_FEE',
    name: 'Mandate Fee',
    ruleType: 'keyword',
    pattern: 'processing.*fee|activation.*fee|service.*charge|withdrawal.*fee',
    severity: 'high',
    score: 16,
    enabled: true,
    description: 'Detects mandatory fee requests',
    category: 'financial',
  },
  {
    id: 'ACCOUNT_THEFT',
    name: 'Account Theft',
    ruleType: 'keyword',
    pattern: 'unauthorized.*transaction|money.*deducted|account.*compromised',
    severity: 'medium',
    score: 10,
    enabled: true,
    description: 'Detects unauthorized transaction or account compromise claims',
    category: 'account_takeover',
  },
  {
    id: 'GAMBLING_SCAM',
    name: 'Gambling/Casino Scam',
    ruleType: 'keyword',
    pattern: 'spin.*win|play.*win.*cash|deposit.*bonus|cashback|sign.*up.*bonus|free.*bonus.*sign|lucky.*draw|jackpot|casino.*online|bet.*win|betting.*app',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects online gambling, casino, or betting scam patterns',
    category: 'scam',
  },
  {
    id: 'FAKE_REWARD',
    name: 'Fake Reward/Giveaway',
    ruleType: 'keyword',
    pattern: 'big.*reward|cash.*out|claim.*prize|lucky.*winner|up.*to.*rs|upto.*rs|daily.*bonus|refer.*friend.*earn|spin.*share.*win',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects fake reward, giveaway, or referral scam patterns',
    category: 'scam',
  },
  {
    id: 'PROMISE_MILLIONS',
    name: 'Promise of Millions',
    ruleType: 'keyword',
    pattern: 'rs\\.?\\s*\\d[\\d,]*,\\d{3}|\\d{1,2},\\d{3},\\d{3}|million.*rupees|lakh.*rupees',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects promises of very large sums of money',
    category: 'scam',
  },
  {
    id: 'WHATSAPP_VERIFY',
    name: 'WhatsApp Verification Code Request',
    ruleType: 'keyword',
    pattern: 'whatsapp.*code|verification.*code.*whatsapp|send.*code.*whatsapp|whatsapp.*verify|enter.*code.*whatsapp|whatsapp.*otp|sms.*code.*whatsapp',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects requests for WhatsApp verification codes — a common account takeover technique',
    category: 'account_takeover',
  },
  {
    id: 'ACCOUNT_LOCKOUT',
    name: 'Account Lockout Threat',
    ruleType: 'keyword',
    pattern: 'account.*lock|account.*deactivat|account.*disabl|account.*verif.*else.*block|verify.*account.*or.*lose|confirm.*identity.*or.*blocked',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects threats about account being locked or deactivated to pressure victims',
    category: 'account_takeover',
  },
  {
    id: 'CNIC_REQUEST',
    name: 'CNIC Number Request',
    ruleType: 'keyword',
    pattern: 'send.*cnic|cnic.*number|cnic.*photo|cnic.*copy|share.*cnic|cnic.*front|cnic.*back|identity.*card.*number|send.*id.*card',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects requests for CNIC or identity card information — potential identity theft',
    category: 'identity_theft',
  },
  {
    id: 'FAKE_DELIVERY',
    name: 'Fake Delivery Scam',
    ruleType: 'keyword',
    pattern: 'delivery.*charge|pay.*delivery|cash.*on.*delivery.*pay|package.*stuck|parcel.*customs|customs.*fee.*parcel|courier.*charge.*pay|delivery.*boy.*pay',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake delivery or package scam patterns where victims are asked to pay for undelivered items',
    category: 'shopping_fraud',
  },
  {
    id: 'FAKE_PRODUCT',
    name: 'Fake Product Listing',
    ruleType: 'keyword',
    pattern: 'original.*100.*percent.*cheap|branded.*replica|first.*copy.*original|imported.*cheap|wholesale.*rate.*single|100.*original.*guarantee.*low.*price',
    severity: 'medium',
    score: 12,
    enabled: true,
    description: 'Detects fake product listing patterns commonly used in online shopping scams',
    category: 'shopping_fraud',
  },
  {
    id: 'CYBERBULLYING',
    name: 'Cyberbullying / Online Harassment',
    ruleType: 'keyword',
    pattern: 'kill.*yourself|kys|go.*die|you.*are.*nothing|everyone.*hates.*you|nobody.*likes.*you|ugly.*stupid.*fat|behen.*lodi|kamini|kameena.*aurat|badcharacter|bad.*character.*woman',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects cyberbullying, online harassment and abusive language patterns',
    category: 'harassment',
  },
  {
    id: 'ONLINE_THREAT',
    name: 'Online Threat / Stalking',
    ruleType: 'keyword',
    pattern: 'i.*know.*where.*you.*live|i.*will.*find.*you|i.*will.*rape|meet.*you.*and.*see|tera.*baap.*aa.*ga|tujhe.*dekhta.*hoo|tera.*pata.*chal.*ja.*ega|follow.*you.*everywhere|watching.*you',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects physical threats, stalking behavior and intimidation online',
    category: 'harassment',
  },
  {
    id: 'SEXTORTION',
    name: 'Sextortion / Blackmail',
    ruleType: 'keyword',
    pattern: 'send.*money.*or.*i.*will.*share.*photos|share.*intimate.*photos|leaked.*your.*photos|nude.*photos.*leak|video.*viral.*kar.*dunga|ashleel.*tasveerein|bheja.*hua.*video.*viral|pay.*or.*photos.*go.*public|send.*nudes.*or.*else',
    severity: 'critical',
    score: 30,
    enabled: true,
    description: 'Detects sextortion and blackmail threats involving intimate images',
    category: 'extortion',
  },
  {
    id: 'FAKE_LOAN_APP',
    name: 'Fake Loan App',
    ruleType: 'keyword',
    pattern: 'instant.*loan.*no.*documents|loan.*without.*documents|quick.*cash.*loan|easy.*loan.*app|loan.*approval.*instant|udhaar.*app|qarz.*fori|loan.*app.*instant.*approval|no.*collateral.*loan.*app',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects fake loan app advertisements and harassment patterns',
    category: 'financial_fraud',
  },
  {
    id: 'LOAN_HARASSMENT',
    name: 'Loan App Harassment',
    ruleType: 'keyword',
    pattern: 'pay.*loan.*or.*we.*will.*send.*photos|loan.*recovery.*agent|pay.*penalty.*loan|extension.*fee.*loan|contact.*list.*access|your.*contacts.*will.*know|send.*payment.*or.*we.*message.*family',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects harassment by fake loan app recovery agents',
    category: 'extortion',
  },
  {
    id: 'TECH_SUPPORT_SCAM',
    name: 'Tech Support Scam',
    ruleType: 'keyword',
    pattern: 'your.*computer.*has.*virus|windows.*is.*infected|install.*anydesk|install.*teamviewer|install.*ultraviewer|remote.*access.*required|microsoft.*calling|google.*support.*calling|your.*system.*is.*compromised',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects fake tech support scam patterns involving remote access tools',
    category: 'tech_fraud',
  },
  {
    id: 'QR_CODE_SCAM',
    name: 'QR Code Payment Fraud',
    ruleType: 'keyword',
    pattern: 'scan.*qr.*to.*receive.*money|scan.*qr.*and.*get.*paid|qr.*code.*receive.*payment|scan.*this.*qr.*to.*win|qr.*scan.*cashback|scan.*qr.*for.*prize|qr.*code.*free.*money',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects QR code payment fraud where victims are tricked into scanning codes',
    category: 'financial_fraud',
  },
  {
    id: 'FAKE_CHARITY',
    name: 'Fake Charity / Donation Scam',
    ruleType: 'keyword',
    pattern: 'donate.*for.*flood.*victims|zakat.*donation.*send.*now|charity.*for.*orphans|donate.*now.*save.*lives|send.*zakat.*to.*this.*account|ramadan.*donation.*urgent|earthquake.*relief.*fund.*send.*money|sadqah.*for.*pakistan',
    severity: 'medium',
    score: 14,
    enabled: true,
    description: 'Detects fake charity and donation scam patterns',
    category: 'scam',
  },
  {
    id: 'FAKE_VISA_SCAM',
    name: 'Fake Visa / Immigration Scam',
    ruleType: 'keyword',
    pattern: 'guaranteed.*visa.*service|work.*visa.*100.*guaranteed|canada.*visa.*agent.*fast|uk.*visa.*guaranteed|dubai.*visa.*instant|australia.*visa.*easy|study.*visa.*guaranteed|visa.*processing.*agent.*fast|iqama.*guaranteed|kafala.*guaranteed',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects fake visa and immigration service scams',
    category: 'scam',
  },
  {
    id: 'RENTAL_SCAM',
    name: 'Rental / Housing Scam',
    ruleType: 'keyword',
    pattern: 'advance.*rent.*for.*flat|token.*money.*for.*house|pay.*advance.*for.*rent|flat.*available.*urgent.*rent|house.*for.*rent.*low.*price.*advance|deposit.*for.*key.*money|pagri.*system.*advance|rent.*agreement.*fee.*advance',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects rental and housing scam patterns where advance payment is demanded',
    category: 'scam',
  },
  {
    id: 'SIM_SWAP',
    name: 'SIM Swap Fraud',
    ruleType: 'keyword',
    pattern: 'sim.*swap.*request|new.*sim.*activated.*your.*number|sim.*port.*request|number.*porting.*request|your.*sim.*will.*be.*replaced|sim.*replacement.*request|mobile.*number.*transferred',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects SIM swap fraud indicators where attacker tries to take over victim phone number',
    category: 'account_takeover',
  },
  {
    id: 'FREELANCE_SCAM',
    name: 'Freelancing / Escrow Scam',
    ruleType: 'keyword',
    pattern: 'pay.*security.*deposit.*for.*project|send.*advance.*to.*start.*work|pay.*registration.*for.*freelance|client.*will.*pay.*after.*you.*send.*deposit|escrow.*payment.*release.*fee|milestone.*fee.*required.*before.*release',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects freelancing and escrow scam patterns targeting online workers',
    category: 'scam',
  },
  {
    id: 'PONZI_SCAM',
    name: 'Ponzi / Pyramid Scheme',
    ruleType: 'keyword',
    pattern: 'member.*get.*member|recruit.*members.*and.*earn|daily.*income.*plan|double.*your.*investment.*daily|chain.*marketing.*income|mlm.*plan.*high.*earning|refer.*10.*people.*earn|network.*marketing.*guaranteed.*income|qnet|onecoin|worldventures',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects Ponzi and pyramid scheme patterns like QNet, OneCoin, chain marketing',
    category: 'scam',
  },
  {
    id: 'FAKE_UNIVERSITY',
    name: 'Fake Educational Institution',
    ruleType: 'keyword',
    pattern: 'admission.*open.*no.*test|guaranteed.*degree.*fast|university.*without.*attendance|online.*degree.*no.*classes|fake.*university.*admission|college.*admission.*without.*entrance|diploma.*in.*3.*months|degree.*in.*6.*months',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects fake educational institution and admission scam patterns',
    category: 'scam',
  },
  {
    id: 'ATM_SKIMMING',
    name: 'ATM/Card Skimming',
    ruleType: 'keyword',
    pattern: 'card.*stuck.*atm|atm.*swallowed.*card|unauthorized.*atm.*withdrawal|card.*cloned|card.*used.*without.*permission|atm.*fraud|someone.*used.*my.*card|card.*charged.*without.*my.*consent',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects ATM card skimming and card cloning fraud patterns',
    category: 'financial_fraud',
  },
  {
    id: 'FAKE_DOCUMENT',
    name: 'Fake Government Document',
    ruleType: 'keyword',
    pattern: 'fast.*track.*passport|domicile.*without.*visit|fake.*cnic.*make|driving.*license.*without.*test|make.*passport.*fast|domicile.*certificate.*agent|noc.*without.*visit|fake.*degree.*make|attestation.*without.*visit',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake government document making services',
    category: 'scam',
  },
  {
    id: 'FAKE_INSURANCE',
    name: 'Insurance Fraud',
    ruleType: 'keyword',
    pattern: 'insurance.*policy.*cheap.*agent|life.*insurance.*guaranteed.*return|fake.*insurance.*policy|insurance.*claim.*rejected|insurance.*agent.*unregistered|health.*insurance.*no.*company|car.*insurance.*cheap.*agent|insurance.*premium.*to.*personal.*account',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake insurance policy and insurance agent fraud patterns',
    category: 'financial_fraud',
  },
  {
    id: 'UTILITY_SCAM',
    name: 'Utility Bill Scam',
    ruleType: 'keyword',
    pattern: 'electricity.*bill.*pay.*now.*or.*disconnect|gas.*meter.*will.*be.*sealed|wapda.*urgent.*payment|k.*electric.*disconnection.*notice|sui.*gas.*bill.*overdue.*pay.*instantly|water.*board.*disconnect.*today|pay.*utility.*bill.*through.*easypaisa.*urgent',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake utility bill scam patterns (WAPDA, gas, water threats)',
    category: 'scam',
  },
  {
    id: 'MATRIMONIAL_SCAM',
    name: 'Fake Matrimonial Scam',
    ruleType: 'keyword',
    pattern: 'rishta.*proposal.*send.*money|shaadi.*urgent.*need.*money|bride.*family.*asking.*for.*money|groom.*visa.*processing.*fee|rishta.*fixed.*send.*gift.*money|shaadi.*before.*nikkah.*advance.*payment|matrimonial.*profile.*need.*financial.*help',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake matrimonial and rishta scam patterns',
    category: 'scam',
  },
  {
    id: 'EXTORTION_CALL',
    name: 'Extortion Call / Phone Blackmail',
    ruleType: 'keyword',
    pattern: 'pay.*money.*or.*we.*will.*file.*case|pay.*or.*we.*will.*send.*police|bhatta.*demand.*pay.*or.*else|we.*know.*your.*address.*pay.*money|pay.*hush.*money.*or.*photos.*leak|fake.*case.*will.*be.*filed.*pay.*money|send.*money.*or.*your.*family.*will.*know',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects extortion and phone blackmail patterns',
    category: 'extortion',
  },
  {
    id: 'FAKE_MEDICINE',
    name: 'Fake Health/Medicine Scam',
    ruleType: 'keyword',
    pattern: 'lose.*weight.*in.*7.*days|cure.*diabetes.*forever|100%.*effective.*herbal.*medicine|weight.*loss.*guaranteed.*no.*diet|hair.*growth.*in.*30.*days.*guaranteed|quack.*doctor.*online.*treatment|desi.*dawa.*for.*all.*diseases|hakimi.*ilaj.*guaranteed.*result',
    severity: 'medium',
    score: 14,
    enabled: true,
    description: 'Detects fake health products, quack medicine and weight loss scam patterns',
    category: 'scam',
  },
  {
    id: 'TASK_SCAM',
    name: 'Work From Home Task Scam',
    ruleType: 'keyword',
    pattern: 'earn.*money.*by.*liking.*videos|earn.*by.*watching.*youtube.*videos|data.*entry.*work.*from.*home.*daily.*payment|form.*filling.*job.*earn.*daily|task.*based.*earning.*pay.*to.*withdraw|upgrade.*to.*vip.*to.*withdraw.*earnings|pay.*fee.*to.*release.*your.*earnings|like.*videos.*earn.*rs.*5000.*daily',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects work from home task scam patterns (video liking, form filling fraud)',
    category: 'scam',
  },
  {
    id: 'COURIER_SCAM',
    name: 'Fake Courier/Delivery Scam',
    ruleType: 'keyword',
    pattern: 'parcel.*stuck.*at.*customs|pay.*customs.*duty.*for.*delivery|your.*package.*held.*at.*airport|courier.*company.*asking.*for.*duty.*payment|OLX.*seller.*sending.*payment.*link|delivery.*charge.*pay.*via.*easypaisa|track.*your.*parcel.*click.*here.*link',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake courier/delivery scam patterns (parcel customs, OLX delivery fraud)',
    category: 'scam',
  },
  {
    id: 'HAJJ_SCAM',
    name: 'Hajj/Umrah Travel Scam',
    ruleType: 'keyword',
    pattern: 'hajj.*package.*cheap.*deal|umrah.*package.*2024.*discount|register.*for.*hajj.*now.*limited.*seats|travel.*agency.*hajj.*visa.*processing.*fee|umrah.*group.*booking.*advance.*payment|hajj.*quota.*guaranteed.*visa.*pay.*now|fake.*travel.*agency.*hajj.*umrah',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake Hajj/Umrah travel agency scam patterns',
    category: 'scam',
  },
  {
    id: 'DIGITAL_PAYMENT_FRAUD',
    name: 'Digital Payment Fraud',
    ruleType: 'keyword',
    pattern: 'easypaisa.*payment.*link.*send.*money|jazzcash.*receive.*payment.*click.*here|send.*rs.*to.*this.*number.*to.*receive.*prize|bank.*transfer.*to.*claim.*your.*amount|fake.*payment.*screenshot.*received|wrong.*number.*transfer.*keep.*it|send.*OTP.*to.*verify.*your.*payment',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects digital payment fraud patterns (EasyPaisa, JazzCash, bank transfer scams)',
    category: 'financial_fraud',
  },
  {
    id: 'SOLAR_SCAM',
    name: 'Fake Solar Panel Scam',
    ruleType: 'keyword',
    pattern: 'solar.*panel.*cheap.*price.*install|free.*solar.*installation.*pay.*later|solar.*system.*5.*year.*warranty.*no.*brand|solar.*panels.*at.*50%.*discount|fake.*solar.*company.*advance.*payment|solar.*panel.*no.*AEDB.*registration|solar.*inverter.*fake.*brand.*cheap',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake solar panel company and installation scam patterns',
    category: 'scam',
  },
  {
    id: 'VEHICLE_SCAM',
    name: 'Vehicle Sale Scam',
    ruleType: 'keyword',
    pattern: 'car.*for.*sale.*below.*market.*price|bike.*sell.*urgent.*advance.*payment|OLX.*car.*listing.*too.*cheap|send.*advance.*to.*book.*this.*vehicle|car.*registration.*book.*copy.*send|vehicle.*auction.*win.*bid.*pay.*now|imported.*car.*duty.*paid.*cheap.*price',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake vehicle sale scam patterns (OLX car/bike listing fraud)',
    category: 'scam',
  },
  {
    id: 'EVENT_SCAM',
    name: 'Event/Trending Scam',
    ruleType: 'keyword',
    pattern: 'pm.*laptop.*scheme.*register.*now|eid.*bonus.*click.*here.*link|14.*august.*azadi.*grant.*apply.*now|relief.*package.*register.*link|ehsaas.*program.*new.*update.*click|kisan.*card.*apply.*online.*link|government.*announced.*scheme.*register.*today|eid.*gift.*claim.*now.*link|independence.*day.*bonus.*click|baitul.*mal.*grant.*apply.*link|prime.*minister.*scheme.*register.*free',
    severity: 'high',
    score: 22,
    enabled: true,
    description: 'Detects event-based trending scam patterns (PM Laptop, Eid bonus, 14 August, relief packages)',
    category: 'scam',
  },
  {
    id: 'AI_DEEPFAKE',
    name: 'AI Voice/Deepfake Scam',
    ruleType: 'keyword',
    pattern: 'send.*money.*urgently.*its.*me.*mom|emergency.*transfer.*money.*now.*its.*dad|voice.*call.*asking.*money.*sounds.*like.*family|ai.*generated.*call.*requesting.*payment|urgent.*wire.*transfer.*family.*emergency.*voice',
    severity: 'critical',
    score: 28,
    enabled: true,
    description: 'Detects AI voice cloning and deepfake scam patterns where scammers impersonate family members',
    category: 'extortion',
  },
  {
    id: 'FAKE_STORE',
    name: 'Fake Online Store Scam',
    ruleType: 'keyword',
    pattern: 'instagram.*shop.*advance.*payment|whatsapp.*store.*pay.*first.*delivery.*later|facebook.*page.*50%.*discount.*bank.*transfer|online.*store.*no.*cod.*only.*advance|branded.*phone.*cheap.*price.*instagram.*only|pay.*advance.*through.*easypaisa.*for.*product',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake online store patterns (Instagram/WhatsApp shops demanding advance payment)',
    category: 'scam',
  },
  {
    id: 'OVERSEAS_JOB',
    name: 'Overseas Employment/Visa Consultancy Scam',
    ruleType: 'keyword',
    pattern: 'dubai.*job.*visa.*processing.*fee.*pay.*now|saudi.*arabia.*work.*visa.*guaranteed.*pay.*agent|uk.*work.*permit.*agent.*fee.*rs.*lakh|canada.*job.*offer.*pay.*consultancy.*fee|overseas.*job.*100%.*visa.*guarantee.*pay.*now|foreign.*company.*hiring.*pay.*processing.*fee|beoe.*unregistered.*agency.*overseas',
    severity: 'high',
    score: 20,
    enabled: true,
    description: 'Detects overseas employment and visa consultancy scam patterns',
    category: 'employment',
  },
  {
    id: 'FAKE_SCHOLARSHIP',
    name: 'Fake Scholarship Scam',
    ruleType: 'keyword',
    pattern: 'hec.*scholarship.*apply.*through.*this.*link|fulbright.*scholarship.*processing.*fee|foreign.*embassy.*scholarship.*register.*now|university.*scholarship.*pay.*application.*fee|fully.*funded.*scholarship.*register.*link.*today|chevening.*scholarship.*apply.*through.*agent|scholarship.*bank.*details.*share.*to.*receive.*money',
    severity: 'high',
    score: 18,
    enabled: true,
    description: 'Detects fake scholarship scam patterns (HEC, Fulbright, embassy impersonation)',
    category: 'scam',
  },
  {
    id: 'FAKE_BANKING_APP',
    name: 'Fake Banking App Scam',
    ruleType: 'keyword',
    pattern: 'download.*banking.*app.*from.*this.*link|install.*hbl.*app.*whatsapp.*link|bank.*update.*app.*install.*qr.*code|banking.*app.*apk.*download.*direct|new.*bank.*app.*install.*now.*link|bank.*security.*update.*install.*app.*urgent|clone.*bank.*app.*install.*for.*reward',
    severity: 'critical',
    score: 25,
    enabled: true,
    description: 'Detects fake banking app scam patterns (clone apps, APK downloads via links)',
    category: 'credential_theft',
  },
];

export class RuleEngine {
  private rules: FraudRule[];

  constructor(rules?: FraudRule[]) {
    this.rules = rules ? [...rules] : [...DEFAULT_RULES];
  }

  analyzeText(text: string): RuleMatch[] {
    // Legitimate context patterns — used to suppress false positives
    const legitimateContexts: Record<string, RegExp> = {
      FAKE_JOB_FEE: /\b(admission|university|college|school|tuition|scholarship|hostel|exam|semester|degree|program|institution|nust|fast\b|uet|board|commission|ministry|government|hospital|clinic|doctor|pharmacy|utility|electricity|gas|water|k\s*electric|ptcl)\b/i,
      MANDATE_FEE: /\b(admission|university|college|school|tuition|scholarship|hostel|exam|semester|degree|program|institution|nust|fast\b|uet|board|commission|ministry|government|hospital|clinic|doctor|pharmacy|utility|electricity|gas|water|k\s*electric|ptcl)\b/i,
    };

    return this.rules
      .filter((rule) => rule.enabled)
      .map((rule) => {
        const result = this.evaluateRule(rule, text);
        // Skip false positives when legitimate institution context is present
        if (result.matched && legitimateContexts[rule.id] && legitimateContexts[rule.id].test(text)) {
          return { ...result, matched: false, evidence: `Rule "${rule.name}" suppressed — legitimate institution context detected` };
        }
        return result;
      });
  }

  analyzeUrl(url: string): RuleMatch[] {
    return this.rules
      .filter((rule) => rule.enabled && (rule.ruleType === 'url' || rule.ruleType === 'domain'))
      .map((rule) => this.evaluateRule(rule, url));
  }

  getRules(): FraudRule[] {
    return [...this.rules];
  }

  addRule(rule: FraudRule): void {
    const existingIndex = this.rules.findIndex((r) => r.id === rule.id);
    if (existingIndex >= 0) {
      this.rules[existingIndex] = { ...rule };
    } else {
      this.rules.push({ ...rule });
    }
  }

  private evaluateRule(rule: FraudRule, input: string): RuleMatch {
    const regex = new RegExp(rule.pattern, 'gi');
    const matches = input.match(regex);

    if (matches && matches.length > 0) {
      return {
        rule,
        matched: true,
        evidence: `Rule "${rule.name}" triggered: found "${matches[0]}" in input`,
        matchedContent: matches[0],
      };
    }

    return {
      rule,
      matched: false,
      evidence: `Rule "${rule.name}" did not match any content in input`,
    };
  }
}
