import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  console.log('Seeding country profiles...');
  const countryProfiles = [
    { name: 'Pakistan', code: 'PK', region: 'South Asia', capital: 'Islamabad', currency: 'PKR', language: 'Urdu/English', educationSystem: 'British-influenced system with HSSC and bachelor degrees', timezone: 'Asia/Karachi', costOfLivingIndex: 25, safetyIndex: 50, qualityOfLifeIndex: 40, popularForStudents: true, overview: 'Pakistan has a large higher education sector with HEC regulating quality.' },
    { name: 'Germany', code: 'DE', region: 'Europe', capital: 'Berlin', currency: 'EUR', language: 'German/English', educationSystem: 'Bologna Process with bachelor/master. Most public universities are tuition-free.', timezone: 'Europe/Berlin', costOfLivingIndex: 65, safetyIndex: 75, qualityOfLifeIndex: 80, popularForStudents: true, overview: 'Germany is a top destination for international students due to tuition-free education.' },
    { name: 'United Kingdom', code: 'GB', region: 'Europe', capital: 'London', currency: 'GBP', language: 'English', educationSystem: 'Russell Group universities with 3-year bachelor and 1-year master degrees', timezone: 'Europe/London', costOfLivingIndex: 75, safetyIndex: 70, qualityOfLifeIndex: 78, popularForStudents: true, overview: 'The UK has world-renowned universities including Oxford, Cambridge, and the Russell Group.' },
    { name: 'United States', code: 'US', region: 'North America', capital: 'Washington D.C.', currency: 'USD', language: 'English', educationSystem: 'Credit-based system with liberal arts education, 4-year bachelor degrees', timezone: 'America/New_York', costOfLivingIndex: 80, safetyIndex: 60, qualityOfLifeIndex: 75, popularForStudents: true, overview: 'The US has the largest number of top-ranked universities globally.' },
    { name: 'Canada', code: 'CA', region: 'North America', capital: 'Ottawa', currency: 'CAD', language: 'English/French', educationSystem: 'Provincial regulation with 4-year bachelor and research-based master/PhD', timezone: 'America/Toronto', costOfLivingIndex: 70, safetyIndex: 80, qualityOfLifeIndex: 85, popularForStudents: true, overview: 'Canada is known for high-quality education, multicultural society, and post-graduation work permits.' },
    { name: 'Australia', code: 'AU', region: 'Oceania', capital: 'Canberra', currency: 'AUD', language: 'English', educationSystem: 'AQF framework with Group of Eight research universities', timezone: 'Australia/Sydney', costOfLivingIndex: 78, safetyIndex: 75, qualityOfLifeIndex: 82, popularForStudents: true, overview: 'Australia offers high-quality education with strong research output.' },
    { name: 'India', code: 'IN', region: 'Asia', capital: 'New Delhi', currency: 'INR', language: 'Hindi/English', educationSystem: 'UGC regulated with 3-4 year bachelor and 2 year master degrees', timezone: 'Asia/Kolkata', costOfLivingIndex: 30, safetyIndex: 55, qualityOfLifeIndex: 50, popularForStudents: true, overview: 'India has IITs, IIMs and many top-ranked institutions.' },
    { name: 'Turkey', code: 'TR', region: 'Middle East', capital: 'Ankara', currency: 'TRY', language: 'Turkish/English', educationSystem: '4-year bachelor, 2-year master, 4-year doctoral structure regulated by YOK', timezone: 'Europe/Istanbul', costOfLivingIndex: 35, safetyIndex: 60, qualityOfLifeIndex: 55, popularForStudents: false, overview: 'Turkey offers affordable education with growing international programs.' },
    { name: 'Malaysia', code: 'MY', region: 'Asia', capital: 'Kuala Lumpur', currency: 'MYR', language: 'Malay/English', educationSystem: 'Malaysian Qualifications Framework with diploma, bachelor, master, and PhD', timezone: 'Asia/Kuala_Lumpur', costOfLivingIndex: 40, safetyIndex: 72, qualityOfLifeIndex: 60, popularForStudents: true, overview: 'Malaysia is an emerging education hub with affordable costs.' },
    { name: 'UAE', code: 'AE', region: 'Middle East', capital: 'Abu Dhabi', currency: 'AED', language: 'Arabic/English', educationSystem: 'KHDA regulated with international branch campuses', timezone: 'Asia/Dubai', costOfLivingIndex: 70, safetyIndex: 85, qualityOfLifeIndex: 75, popularForStudents: true, overview: 'UAE hosts branch campuses of top global universities.' },
    { name: 'Ireland', code: 'IE', region: 'Europe', capital: 'Dublin', currency: 'EUR', language: 'English', educationSystem: 'NFQ framework with 3-4 year bachelor and 1-2 year master', timezone: 'Europe/Dublin', costOfLivingIndex: 72, safetyIndex: 78, qualityOfLifeIndex: 80, popularForStudents: true, overview: 'Ireland is a top English-speaking destination in Europe with strong tech industry.' },
    { name: 'Netherlands', code: 'NL', region: 'Europe', capital: 'Amsterdam', currency: 'EUR', language: 'Dutch/English', educationSystem: 'Research universities and universities of applied sciences', timezone: 'Europe/Amsterdam', costOfLivingIndex: 70, safetyIndex: 80, qualityOfLifeIndex: 85, popularForStudents: true, overview: 'Netherlands offers many English-taught programs at affordable costs.' },
    { name: 'New Zealand', code: 'NZ', region: 'Oceania', capital: 'Wellington', currency: 'NZD', language: 'English', educationSystem: 'NZQF framework with 3-year bachelor and 1-2 year master', timezone: 'Pacific/Auckland', costOfLivingIndex: 72, safetyIndex: 82, qualityOfLifeIndex: 85, popularForStudents: false, overview: 'New Zealand offers high-quality education in a safe environment.' },
    { name: 'Sweden', code: 'SE', region: 'Europe', capital: 'Stockholm', currency: 'SEK', language: 'Swedish/English', educationSystem: 'Bologna Process with 3-year bachelor and 2-year master', timezone: 'Europe/Stockholm', costOfLivingIndex: 75, safetyIndex: 82, qualityOfLifeIndex: 88, popularForStudents: false, overview: 'Sweden is known for innovation and English-taught programs.' },
    { name: 'Switzerland', code: 'CH', region: 'Europe', capital: 'Bern', currency: 'CHF', language: 'German/French/English', educationSystem: 'ETH domain universities with strong research focus', timezone: 'Europe/Zurich', costOfLivingIndex: 95, safetyIndex: 88, qualityOfLifeIndex: 95, popularForStudents: true, overview: 'Switzerland has ETH Zurich and EPFL among the top technical universities.' },
    { name: 'France', code: 'FR', region: 'Europe', capital: 'Paris', currency: 'EUR', language: 'French/English', educationSystem: 'Grandes Ecoles and university system with Licence/Master/Doctorat', timezone: 'Europe/Paris', costOfLivingIndex: 72, safetyIndex: 65, qualityOfLifeIndex: 78, popularForStudents: true, overview: 'France has Sorbonne and Paris-Saclay among top global institutions.' },
    { name: 'South Africa', code: 'ZA', region: 'Africa', capital: 'Pretoria', currency: 'ZAR', language: 'English/Afrikaans', educationSystem: 'NQF framework with 3-4 year bachelor and 1-2 year master', timezone: 'Africa/Johannesburg', costOfLivingIndex: 42, safetyIndex: 40, qualityOfLifeIndex: 50, popularForStudents: false, overview: 'South Africa has the top-ranked universities in Africa.' },
    { name: 'Philippines', code: 'PH', region: 'Asia', capital: 'Manila', currency: 'PHP', language: 'English/Filipino', educationSystem: 'CHED regulated with 4-year bachelor and 2-year master', timezone: 'Asia/Manila', costOfLivingIndex: 32, safetyIndex: 50, qualityOfLifeIndex: 48, popularForStudents: false, overview: 'Philippines offers affordable English-medium education.' },
    { name: 'Thailand', code: 'TH', region: 'Asia', capital: 'Bangkok', currency: 'THB', language: 'Thai/English', educationSystem: 'MHESI regulated with 4-year bachelor and 2-year master', timezone: 'Asia/Bangkok', costOfLivingIndex: 38, safetyIndex: 60, qualityOfLifeIndex: 55, popularForStudents: false, overview: 'Thailand is an emerging education destination in Southeast Asia.' },
    { name: 'Hungary', code: 'HU', region: 'Europe', capital: 'Budapest', currency: 'HUF', language: 'Hungarian/English', educationSystem: 'Bologna Process with 3-year bachelor and 2-year master', timezone: 'Europe/Budapest', costOfLivingIndex: 45, safetyIndex: 72, qualityOfLifeIndex: 65, popularForStudents: false, overview: 'Hungary offers affordable EU education with English programs.' },
    { name: 'Poland', code: 'PL', region: 'Europe', capital: 'Warsaw', currency: 'PLN', language: 'Polish/English', educationSystem: 'Bologna Process with 3-year bachelor and 2-year master', timezone: 'Europe/Warsaw', costOfLivingIndex: 42, safetyIndex: 70, qualityOfLifeIndex: 65, popularForStudents: false, overview: 'Poland has growing number of English-taught programs at low costs.' },
    { name: 'Russia', code: 'RU', region: 'Europe', capital: 'Moscow', currency: 'RUB', language: 'Russian/English', educationSystem: 'Specialist and Bologna system with 4-year bachelor and 2-year master', timezone: 'Europe/Moscow', costOfLivingIndex: 38, safetyIndex: 55, qualityOfLifeIndex: 55, popularForStudents: false, overview: 'Russia has Lomonosov Moscow State University among top global institutions.' },
    { name: 'Brazil', code: 'BR', region: 'South America', capital: 'Brasilia', currency: 'BRL', language: 'Portuguese', educationSystem: 'MEC regulated with 4-year bachelor and 2-year master', timezone: 'America/Sao_Paulo', costOfLivingIndex: 38, safetyIndex: 45, qualityOfLifeIndex: 55, popularForStudents: false, overview: 'Brazil has USP among the top universities in Latin America.' },
    { name: 'Egypt', code: 'EG', region: 'Africa', capital: 'Cairo', currency: 'EGP', language: 'Arabic/English', educationSystem: 'Supreme Council of Universities regulated system', timezone: 'Africa/Cairo', costOfLivingIndex: 28, safetyIndex: 50, qualityOfLifeIndex: 45, popularForStudents: false, overview: 'Egypt has Cairo University and AUC among top institutions in Africa.' },
    { name: 'Saudi Arabia', code: 'SA', region: 'Middle East', capital: 'Riyadh', currency: 'SAR', language: 'Arabic/English', educationSystem: 'Ministry of Education regulated with growing international programs', timezone: 'Asia/Riyadh', costOfLivingIndex: 50, safetyIndex: 75, qualityOfLifeIndex: 65, popularForStudents: false, overview: 'Saudi Arabia is investing heavily in higher education with generous scholarships.' },
  ];

  for (const cp of countryProfiles) {
    await prisma.countryProfile.upsert({
      where: { code: cp.code },
      update: cp,
      create: cp,
    });
    console.log(`  Created/Updated: ${cp.name} (${cp.code})`);
  }
  console.log(`\nDone! ${countryProfiles.length} country profiles seeded.`);
}

main()
  .catch((e) => { console.error('Failed:', e.message); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
